# .goreleaser.yml
version: 2

project_name: erebus

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: erebus
    main: .
    binary: erebus
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildTime={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
        # 暂时忽略 darwin/arm64，除非你有 M1 Mac 测试环境

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - etc/erebus.yaml
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  groups:
    - title: New Features
      regexp: "^.*feat[(:].*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix[(:].*$"
      order: 1
    - title: Other Changes
      order: 999

release:
  github:
    owner: your-username
    name: erebus
  # 如果有 Homebrew tap，可以取消注释
  # homebrew:
  #   name: erebus
  #   commit_author:
  #     name: goreleaserbot
  #     email: bot@goreleaser.com
  #   folder: Formula
  #   homepage: "https://github.com/your-username/erebus"
  #   description: "Erebus - Your application description"

snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
# 如果需要 Docker 镜像，取消注释以下部分
# - image_templates:
#     - "your-username/erebus:{{ .Version }}"
#     - "your-username/erebus:latest"
#   goos: linux
#   goarch: amd64
#   dockerfile: Dockerfile
#   use: buildx